### ISSUE TITLE
Album Art image Resolution

### ISSUE THREAD

**Issue by jonghee5** [jaymarnz/bluview#2] opened 2023-12-13 12:09 UTC
It seems that a low resolution image was used. Could you please use a higher resolution image?

**Comment by jaymarnz** [comment] 2023-12-13 17:43
Thanks for posting the issue. The album art is provided by the BluOS device itself. It is intended for the BluOS mobile app so perhaps certain art displayed in a larger size is what you are seeing. BluView doesn't manipulate the image the device provides but the difference in image size between the app and BluView might be what you are seeing. Maybe that is noticeable at certain screen sizes.

Does the album art look different on the BluOS mobile app vs. BluView?
What device are you running BluView? What is its screen size in pixels so I can try to reproduce it?
Can you post a screenshot of the BluOS mobile app and the BluView screen playing the same song?
What is the source you are playing? Is it your local music collection or streaming? If streaming, what service and song?
What is your BluOS device and firmware version?

**Comment by jonghee5** [comment] 2023-12-21 12:11
Sorry for the late response.
I compared with BlueOS App and BlueView.

When listening to music through Tidal streaming, the album art resolution is very high in the BlueOS app, but the resolution in BlueView is low.
When playing local library music, the BlueOS and BlueView resolutions appear to be the same.

**Comment by jaymarnz** [comment] 2023-12-22 10:30
Thanks again for the additional info and taking the time to report this issue.

I've dug into this and believe I've found an undocumented fix for it in the BluOS API. However, I wasn't able to test whether the same issue occurs on all music sources but did test Tidal, Spotify and local music. As you noted, local library wasn't affected and neither is Spotify. So the change I made only applies to Tidal. Unless this issue shows up with another music source it should be done.

Please give it a try and let me know if it solves your problem and I'll close this issue.

**Comment by jonghee5** [comment] 2023-12-24 11:26
Album art is now displayed at the same resolution as in the Tidal app.

Thank you for your hard work.

**Closed as completed** 2023-12-24 11:26 UTC
